name: pipebreak
version: "1.0.0"
config-version: 2
profile: pipebreak

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  pipebreak:
    staging:
      +materialized: view
    marts:
      +materialized: table
